### PR TITLE
Added to_bit_array

### PR DESCRIPTION
**Pull request by MoeDevelops**
Added to_bit_array as a public function
It returns the value of the UUID.

The private helper function to_bit_array got changed to to_bit_array_helper

### CODE REVIEW

**Review by lpil — COMMENTED** [review]
What's the motivation for this addition?

**Comment by MoeDevelops** [comment]
When sending the uuid its more efficient to do it as a bit array instead of a string. As UUID is a opaque type the value isn't accessible to the user of the library.

**Comment by MoeDevelops** [comment]
Also useful for storing the uuid. The way it would be done right now is to convert it to a string and then to a bit array, which causes unnecessary computing

**Review by lpil — COMMENTED** [review]
Makes sense! Thank you.

Could you add a set of tests for each of the uuid types and update the changelog please? Thank you

**Comment by MoeDevelops** [comment]
Sure, I will do that!

**Comment by MoeDevelops** [comment]
I added tests and updated the changelog

**Comment by MoeDevelops** [comment]
While I'm on it I could also add from_bit_array(). For the same purpose as I said but for reading/receiving the uuid.

**Review by lpil — APPROVED** [review]
Very nice!!

**Pull request merged**
